### ISSUE TITLE
[color-gradients] Idea for a higher-level interface.

### ISSUE THREAD

**Issue by harold** [techascent/tech.datatype#16]
Had some thoughts about `color-gradients` interfaces today.

At the moment, I'm using `gradient-name->gradient-line`, and then making an `int32-reader` off the returned gradient, and then using `.read2d` on the reader to get the r/g/b byte values.

This is a little verbose and error prone (reading off the end of the reader throws, for instance.

An interface like this might be nice:
```clojure
(for [p [0.0 0.2 0.4 0.6 0.8 1.0]]
  (let [[b g r] (color-gradients/lookup :red-green p)]
    (println [r g b])))
```

**Comment by cnuernber** [comment]
Fixed:
https://github.com/techascent/tech.datatype/releases/tag/4.68a

Tested:
https://github.com/techascent/tech.datatype/blob/master/test/tech/v2/tensor/color_gradient_test.clj#L32

For future reference or in case you are curious, here is the code to do this:
```clojure
(defn colorize->clj
  "Same as colorize but returns a ND sequence of [b g r] persistent vectors.
  For options, see documentation in colorize."
  [src-tens gradient-name & options]
  (when (seq src-tens)
    (let [src-dims (dtype/shape src-tens)]
      (-> (apply colorize src-tens gradient-name options)
          ;;In case of 1d.  colorize always returns buffered image which is always
          ;;2d.
          (dtt/reshape (concat src-dims [3]))
          (dtt/->jvm)))))
```

**Comment by harold** [comment]
Niice. Look forward to doing this next time! :clap:
