### ISSUE TITLE
operator as sequential

### ISSUE THREAD

**Issue by genmeblog** [techascent/tech.datatype#27]
Can you mark each op/reader as `Sequential`?

Why I need this. Op (like `dfn/+`) returns reified object which is `seqable` (because it is Iterable).

When I test if something is `seqable` I can catch String and Map (maybe other stuff). `sequential` is a narrow test simply says that the object is list (in common sense) of simple values.

**Comment by cnuernber** [comment]
Good catch.  Yes, it appears that is a super safe change.

**Comment by cnuernber** [comment]
The one question I have is why doesn't `java.lang.RandomAccess` imply Sequential?

**Comment by genmeblog** [comment]
Clojure checks if objects implement Sequential interface only. It acts as a tag in this case. `sequable?` is different story.
