### ISSUE TITLE
seq of keywords can't be converted to reader

### ISSUE THREAD

**Issue by genmeblog** [techascent/tech.datatype#29]
```clojure
(->reader [:a :b] {:datatype :keyword})
;; => [:a :b]

(->reader '(:a :b) {:datatype :keyword})
;; => nil
```

**Comment by cnuernber** [comment]
Seq's aren't random access containers, ->reader only works when the underlying storage is RA.

**Comment by genmeblog** [comment]
ah, ok. Sometimes such issues are not obvious. Closing then.

**Comment by cnuernber** [comment]
agreed, probably a documentation issue really.

**Comment by harold** [comment]
I could imagine it logging a warning here, maybe?
