### ISSUE TITLE
reader can have any type

### ISSUE THREAD

**Issue by genmeblog** [techascent/tech.datatype#32]
Why is it allowed?

```clojure
(dtype/->reader [1 2 3] :random-type)
;; => [1 2 3]

(col/new-column :what-is-the-type? (dtype/->reader [1 2 3] :random-type))
;; => #tech.ml.dataset.column<random-type>[3]
;;    :what-is-the-type?
;;    [1, 2, 3, ]
```

I would expect validation of provided types.

**Comment by cnuernber** [comment]
There is no validation at all of object datatypes (a keyword that doesn't map to a known primitive datatype) and primitive datatypes are only validated on read.  We have a map of datatype->expected-object type so potentially we could throw if the datatype isn't in this map and if it is apply a reader that checks that every value read is either in the null set or is an instance of the expected object datatype.

I get checking to work correctly for unsigned/signed types and minimal checking if you write to a container of a specific datatype else the system expects that you are using type erasure of something like that and thus punts and goes with generic object datatype containers.

Typesystems are hard :-).  Not sure how far down that road we really want to go but getting a reader is a constant time operation which precludes scanning the data to ensure it matches a given expectation.  Hence the issues earlier with column-cast.

**Comment by genmeblog** [comment]
I don't expect to check every value in the reader. That's not the point. When creating reader or column with provided datatype - just assert that such datatype is supported by the library. 

I've made a typo in one place and had no possibility to find the bug early.

```clojure
(dtype/->reader [1 2 3] :keyword) ;; passes
(dtype/->reader [1 2 3] :blah) ;; error
```

**Comment by cnuernber** [comment]
This is reasonable to me.  And catching that type of mistype is important; more important than having readers of denoted by totally arbitrary types.
